### ISSUE TITLE
Improved Application Dependencies Management

### ISSUE THREAD

**Issue by Gibson-Gichuru** [SpaceyaTech/mastori#134]
**Description:**
The current method of listing application dependencies in a text file is proving to be challenging to track and manage effectively. I suggest implementing a more managed approach to handle dependencies, such as utilizing a package manager or dependency management tool.

**Comment by sangkips** [comment]
@Gibson-Gichuru I will like to take up this issue but can you please provide more context

**Comment by Gibson-Gichuru** [comment]
> @Gibson-Gichuru I will like to take up this issue but can you please provide more context

Ok Sure what I have in mind is try to separate the production required dependencies from the dev dependencies. We can have 3 .txt files i.e common.txt, production.txt and dev.txt. The common.txt file will contain the dependencies that cut across the two environments and the other two files contain only dependencies required by the given environment

**Comment by tony-nyagah** [comment]
> @Gibson-Gichuru I will like to take up this issue but can you please provide more context

Are you still looking at taking up this issue? I can look into it if not.

**Comment by Gibson-Gichuru** [comment]
> > @Gibson-Gichuru I will like to take up this issue but can you please provide more context
> 
> Are you still looking at taking up this issue? I can look into it if not.

You can take the issues

**Comment by tony-nyagah** [comment]
I submitted a pull request that closes this issue. Could you look at it @JimmyTron?
