### ISSUE TITLE
Unauthorized session can create new categories

### ISSUE THREAD

**Issue by collinskasyoki** [SpaceyaTech/mastori#145]
**Describe the bug**
Sending a POST request on the 'categories' endpoint with a category name creates a new category. This happens even on an anonymous session without having provided login credentials or a valid token.

**To Reproduce**
1. Go to the 'categories' URL. If running locally, go to 'http://localhost:8000/categories'
2. Create a POST request with an input called 'name' and a value of any category name
3. Submit the request

**Expected behavior**
The endpoint should reject the request and prompt for authentication credentials before creating the new category.

**Screenshots**
![image](https://github.com/SpaceyaTech/mastori/assets/40399921/7a2593f0-93f4-4a04-9bd5-b3c678b28832)
The screenshot shows that the category is successfully created in an unauthorized environment.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser [Brave]
 - Version [1.56.14 Chromium: 115.0.5790.114 (Official Build) (64-bit)](https://brave.com/latest/)]

**Comment by sangkips** [comment]
@hellen-22 can you have a look at this, if you have any issues ping me up
