### ISSUE TITLE
Blog Comments

### ISSUE THREAD

**Issue by JimmyTron** [SpaceyaTech/mastori#82]
**The blog comments should have the following fields : **

- [ ] id( unique id)
- [ ] body -the content of the comment
- [ ] user id (FK) -links the comment to a specific user who created/ commented
- [ ] post id (FK) -link the comment to a specific post
- [ ] date created
- [ ] date flagged
- [ ] List of Reactions

**Additional context**
Add any other Functionality that seems necessary
this is a screenshot of [Medium](https://medium.com)
![image](https://user-images.githubusercontent.com/23496280/212439392-7e606408-4363-45ef-904b-74bcc89a41ee.png)

**Comment by Eugene-Kwaka** [comment]
Got it..will work on it
