### ISSUE TITLE
Reactions

### ISSUE THREAD

**Issue by JimmyTron** [SpaceyaTech/mastori#86]
# Reactions 

- [ ] id(unique id)
- [ ] type -( up vote/down vote or like/dislike)- enumerated value
- [ ] user_id (FK) - links the reaction to a specific user who created it
- [ ] post_id
- [ ] comment_id
- [ ] date created,updated

The reactions are in a way used to communicate emmotions without having to acctually reply to the blog or comment

**Comment by Fredrick-Waihenya** [comment]
how can I help to complete this milestone.

**Comment by Fredrick-Waihenya** [comment]
Do we need this reaction: type -( up vote/down vote or like/dislike)- enumerated value shouldn't we just use  an up vote only in this case.

**Comment by JimmyTron** [comment]
> 

that could be interesting, but first give more context on how you could do that?
 and maybe just go ahead

**Comment by Fredrick-Waihenya** [comment]
We should have a like button where the number increases on click, the icon is to be determined by the front-end to avoid overcrowding.
